<?php

/**
 * @file
 * Contains no hooks, just information.
 */

/**
 * Implements hook_views_data_alter().
 */
function custom_views_field_views_data_alter(array &$data) {
  $data['node_field_data']['custom_field_conditional_phone'] = [
    'title' => t('Custom Field Conditional Phone'),
    'help' => t('Provides a custom field conditional phone.'),
    'field' => [
      'id' => 'custom_field_conditional_phone',
    ],
  ];
}
